name: part2
on: push

jobs:
    createart:
        runs-on: ubuntu-latest
        steps:
            - name: Create Artifact
              run:  echo username : ${{ vars.USERNAME }} and password : ${{ secrets.PASSWORD}} > elite.txt
            - name: display artifact
              run: cat elite.txt
   