name: part1
on: push

jobs:
    createart:
        runs-on: ubuntu-latest
        steps:
            - name: Create Artifact
              run: echo "This is part 1" > elite.txt
            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: elite-artifact
                path: elite.txt
    downloadart:
        needs: createart
        runs-on: ubuntu-latest
        steps:
            - name: downloadartifact
              uses: actions/download-artifact@v4
              with:
                name: elite-artifact
            - name: display-art
              run: cat elite.txt
