name: part2
on: push

jobs:
    createart:
        runs-on: ubuntu-latest
        steps:
            - name: Create Artifact
              run:  echo "this is Part 1" > elite.txt
            - name: display artifact
              run: cat elite.txt
   