name: part2
on: push
env:
  filename: elite.txt
jobs:
    createart:
        runs-on: ubuntu-latest
        steps:
            - name: Create Artifact
              run:  echo username ${{ vars.username}} password ${{secrets.password}} > $filename
            - name: display artifact
              run: cat $filename
   